# This file was generated by GoReleaser. DO NOT EDIT.
cask "wallapop" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "ddab2ccaeea3e27b96239ca65a49cc13c2bbf3b0a4b4677686d7a867cb4a4d6f"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bdde320086c392adba7f50a418e7782480c5cc7e4b83379dd09dab2d9b4af2d0"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9dbee23297bd4fd9bb779a56443f58181c2dc565ca7192f26f305f6d6ca21908"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e0a10caeb47ba426ae4e804a62288f45cf1d3f6b6253656b72016d01970f197"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wallapop"
  desc "Terminal CLI for Wallapop"
  homepage "https://github.com/Microck/wallapop-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wallapop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wallapop"]
    end
  end

  # No zap stanza required
end
