# This file was generated by GoReleaser. DO NOT EDIT.
cask "wallapop" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "2eb3e163c67f777c746b1a12ba92003fa1953908551df3d8c669a5dfc874b6ee"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd13f727c01e75136d140f07ed38e18888a43f2632836467828a31535588e03b"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3d626776590962692fc06d702296611e2e73ba1301bd06898114e97dd6e2a04e"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a445bdd4be9428046b81f969712dcddabb53639c3f656953296811e6be35541"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wallapop"
  desc "Terminal CLI for Wallapop"
  homepage "https://github.com/Microck/wallapop-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wallapop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wallapop"]
    end
  end

  # No zap stanza required
end
