# This file was generated by GoReleaser. DO NOT EDIT.
cask "wallapop" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "4d3bdcfb6c292844c436f14ee87e3db23f1785709c9d055881dcfbadd2d217a4"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03ca5a0b35dd8d3f7a9b193cab931e16c03fa0f2c788da32907e23183f5f988e"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c323f784ecd91c4c3b49b56961e7b83cb1b1105681334c4c3f22fba68149587b"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f4920a680df53862fe2dd2bf4ea65bcbaeb9bc90f4de0e86feefef92715d7ef"
      url "https://github.com/Microck/wallapop-cli/releases/download/v#{version}/wallapop_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wallapop"
  desc "Terminal CLI for Wallapop"
  homepage "https://github.com/Microck/wallapop-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wallapop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wallapop"]
    end
  end

  # No zap stanza required
end
